### ISSUE TITLE
Compile with old GHC

### ISSUE THREAD

**Issue by Ongy** [rblaze/haskell-dbus#2]
When I run travis-ci with the (admittedly old) ghc 7.6 which sadly is the current debian-jessie version, I ran into an compile error on the dbus package.

https://travis-ci.org/Ongy/monky/jobs/236682148#L1207

**Comment by rblaze** [comment]
Sorry about late response, somehow I ended up without notifications for this project.

Looks like bytestring-builder was merged into bytestring library since then. If you still need to use older compiler, feel free to send pull request adding dependency to bytestring-builder conditionally, depending on ghc version.

**Comment by Ongy** [comment]
Oh, I didn't remember this was a thing.
Erm, I think I recently removed that travis job either way. And current debian stable, (which is the oldest *I* care about) moved on. So I'll close this.
