### ISSUE TITLE
Generation just picks the first interface in the file.

### ISSUE THREAD

**Issue by LeifW** [rblaze/haskell-dbus#23]
Given the following `snapper.xml`
```xml
<node name='/org/opensuse/Snapper'>
  <interface name='org.freedesktop.DBus.Introspectable'>
    <method name='Introspect'>
      <arg name='xml_data' type='s' direction='out'/>
    </method>
  </interface>
  <interface name='org.opensuse.Snapper'>
    <signal name='ConfigCreated'>
      <arg name='config-name' type='s'/>
    </signal>
    <signal name='ConfigModified'>
      <arg name='config-name' type='s'/>
    </signal>
    <signal name='ConfigDeleted'>
      <arg name='config-name' type='s'/>
    </signal>
    ...
  </interface
</node
```
Running the following Template Haskell:
```haskell
generateFromFilePath defaultGenerationParams { genBusName = Just "org.opensuse.Snapper"
                                             , genObjectPath = Just "/org/opensuse/Snapper"
                                             , genInterfaceName = "org.opensuse.Snapper"
                                             } "snapper.xml"
```
only gives me the following method:
```
introspectMethodCall :: DBus.Internal.Message.MethodCall
introspect ::
  Client -> IO (Either DBus.Internal.Message.MethodError String)
```
Which is the one in the first interface, `org.freedesktop.DBus.Introspectable`. I was hoping for the methods in the second interface in the file, `org.opensuse.Snapper`.

**Comment by colonelpanic8** [comment]
@LeifW Yeah, that is the expected behavior of generateFromFilePath.

https://github.com/rblaze/haskell-dbus/blob/6f923bfd2c7ee58bee5281e9006fe92a42f49774/lib/DBus/Generation.hs#L541

This needs to be documented, but I think you may be misunderstanding the purpose of the generationParams. They are there so that it is possible to provide default values for Bus, ObjectPath and InterfaceName so that those need to be provided to each method call. They do not select the appropriate interface from the file.

The reason this is necessary, is that some dbus interfaces will be used on

- multiple object paths
- multiple bus names

This is true of things like:

MPRIS
StatusNotifierItem
etc etc.

for your xml file, I would recommend you simply remove the introspectable interface in the file. haskell-dbus already has the full introspection interface built in by default.

**Comment by colonelpanic8** [comment]
@LeifW If you REALLY want to generate all the interfaces in the file with the same PARAMS (but really do you want to do this?) You can just use something like:

```
generateFromFilePath :: GenerationParams -> FilePath -> Q [Dec]
generateFromFilePath generationParams filepath =
  let obj = unsafePerformIO $
            head . maybeToList . I.parseXML "/" <$> readFile filepath
      clientsAndSignals interface = fmap (++) signals <*> client
        where
        signals = generateSignalsFromInterface generationParams interface
        client = generateClient generationParams interface
  in concat <$> mapM clientAndSignals $ I.objectInterfaces obj
```

But actually, you should probably avoid the unsafePerformIO all together, since you can do IO in the Q monad.

This is what status-notifier-item does:

https://github.com/ivanmalison/status-notifier-item/blob/738197e4dc56aa6bf7f3c99c0759e5b797540b0e/src/StatusNotifier/Util.hs#L24
