### ISSUE TITLE
dbus depends on deprecated version of xml-conduit

### ISSUE THREAD

**Issue by peti** [rblaze/haskell-dbus#40]
The latest version of dbus depends on xml-conduit 1.9.x, but that version has been deprecated on Hackage. So, what version am I supposed to pick now?

**Comment by rblaze** [comment]
Use stackage? I'm not sure what "deprecation" means for packages anyway. Is entire package going to be unmaintained from now on, or this specific version is dead-end, and next would be incompatible again?

**Comment by peti** [comment]
> I'm not sure what "deprecation" means for packages anyway.

In the specific case of `xml-conduit 1.9.0.0` I reckon the deprecation means that this particular release contains some significant design flaw or something along those lines. Whether a new version in the 1.9.x range comes out or not depends on whether that flaw can be remedied in a way that does not change the API or not. I suppose @snoyberg would know.

Anyhow, the problem remains that it's currently not possible to build `dbus` with ghc-8.8.1 without relying on dependencies that their respective authors deprecated because of serious issues.

**Comment by rblaze** [comment]
My rule of thumb [and primary motivation to update dependencies] is to follow stackage-nightly dependencies. Otherwise, it is too much trouble getting my packages into the next version. Between using the deprecated version and having the package removed from stackage snapshot, I'll take a deprecated version.

Unfortunately, 1.9.x is slightly incompatible with 1.8.x, so I can't make `dbus` compile with both.
